In [24]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [25]:
dataset = pd.read_csv('Employee.csv')
dataset.head()

,Company,Age,Salary,Place,Country,Gender
0,TCS,20.0,NaN,Chennai,India,0
1,Infosys,30.0,NaN,Mumbai,India,0
2,TCS,35.0,2300.0,Calcutta,India,0
3,Infosys,40.0,3000.0,Delhi,India,0
4,TCS,23.0,4000.0,Mumbai,India,0


In [26]:
X = dataset.iloc[:, :-1].values   # all columns except the last (Gender)
y = dataset.iloc[:, -1].values    # only the last column (Gender)

In [27]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])            # Age is column index 1, Salary is index 2
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [28]:
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(sparse_output=False), [0, 3, 4])],  # Company, Place, Country
    remainder='passthrough'
)
X = np.array(ct.fit_transform(X))

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [30]:
sc = StandardScaler()
X_train[:, -2:] = sc.fit_transform(X_train[:, -2:])   # scale Age and Salary
X_test[:, -2:] = sc.transform(X_test[:, -2:])

In [31]:
print("X_train:\n", X_train)
print("\nX_test:\n", X_test)
print("\ny_train:\n", y_train)
print("\ny_test:\n", y_test)

X_train:
 [[0.0 0.0 0.0 ... 1.0 -1.0678346011711433 -0.18513923840222982]
 [0.0 0.0 1.0 ... 1.0 -0.8702973045867367 1.455951759207182]
 [0.0 0.0 0.0 ... 1.0 -0.0322833117690429 0.22826217965342022]
 ...
 [0.0 0.0 0.0 ... 1.0 -0.6727600080023302 -0.058545903538178255]
 [0.0 0.0 1.0 ... 1.0 1.302612957841735 -0.5918661633308461]
 [0.0 0.0 0.0 ... 1.0 0.41369512321190566 -0.058545903538178255]]

X_test:
 [[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 -0.8702973045867367 -0.058545903538178255]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 -3.0432075670152083 -1.7599024605617442]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 1.0 -0.9690659528789399 0.45519494597256616]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 1.302612957841735 -0.5918661633308461]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 1.0 1.302612957

In [32]:
print(dataset.isnull().sum())

Company     8
Age        18
Salary     24
Place      14
Country     0
Gender      0
dtype: int64


In this assignment, I performed data preprocessing on the Employee dataset. I handled missing values in the Age and Salary columns using mean imputation, encoded categorical variables (Company, Place, Country) using one-hot encoding, split the dataset into training and test sets (80/20 split), and applied feature scaling to normalize the Age and Salary columns.

In [33]:
cleaned_df = pd.DataFrame(X_train)
cleaned_df.to_csv('Cleaned_Employee_Train.csv', index=False)